#!/bin/bash
user=$(awk -F "=" '/user/ {print $2}' /opt/server.ini | xargs)
chmod +x ./systemd/heart_start
sudo ln -s /home/$user/heart/systemd/heart.service /etc/systemd/system/
sudo ln -s /home/$user/heart/systemd/heart_start /opt/
sudo ln -s /home/$user/heart/server.ini /opt/
sudo systemctl enable heart
sudo systemctl daemon-reload
sudo systemctl start heart.service